### PR TITLE
Update FakeApiDescriptionGroupCollectionProvider.cs

### PR DESCRIPTION
**Pull request by pranavkm**
Do you know how or why this fails?

### CODE REVIEW

**Comment by tebeco** [comment]
(i'll remove those comment and try to get more info on the failing tests)
the code you removed help me identify one of the 6 test by changing the line 1 by either : 
`#define EMPTY` or `FORK_V2` or `FORK_V3`

if you re-add the code and run the test in va you might see more info on that specific test

(BRB)

**Comment by tebeco** [comment]
This is just the first test i'm trying to get a grip onto where i could check the behavior of `internal` vs `empty one

The 5 other also have weird generated Data in the `OpenApiDocument`

**Comment by tebeco** [comment]
in the 5 leftovers, 3 are running in the same `[Theory]` they all check the `ContentType` : 
https://github.com/tebeco/Swashbuckle.AspNetCore/blob/master/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs#L434-L436

The [assertion here](https://github.com/tebeco/Swashbuckle.AspNetCore/blob/master/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs#L454) : 
```
Assert.Equal(expectedContentTypes, response.Content.Keys);
```
except to see (by default probably) the a list of value as a `ContentType` with the value `"application/json", "text/json" ` but it `Empty`
(not sure how it is supposed to be generated)

**Comment by tebeco** [comment]
One test is very interresting as it test that `CancellationToken` is not supposed to be generated as a parameter ;)
https://github.com/tebeco/Swashbuckle.AspNetCore/blob/master/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs#L322 :
```
        [Fact]
        public void GetSwagger_IgnoresParameters_IfApiParameterIsCancellationToken()
        {
            var subject = Subject(setupApis: apis => apis
                .Add("GET", "collection", nameof(FakeController.AcceptsCancellationToken)));

            var swagger = subject.GetSwagger("v1");

            var operation = swagger.Paths["/collection"].Operations[OperationType.Get];
            Assert.Empty(operation.Parameters);
        }
```

The `Action` being tested look like this :
`        public void AcceptsCancellationToken(CancellationToken cancellationToken) {}`


and the result is ... un excepted 
image

**Comment by tebeco** [comment]
and for the last one it seems that the `OpenApi` generation ignores the `[Produces]` Attributes :  
```
        [Produces("application/xml")]
        public ComplexType AnnotatedWithProduces()
        {
            throw new NotImplementedException();
        }

```

**Comment by pranavkm** [comment]
@tebeco sorry I hadn't tried building the app. You're right, those types aren't public. These tests are trying to stay true to MVC"s setup, substituting them with a stub is likely why you see the test failures. One way to proceed would be to have MVC construct this type for you. For instance:

```C#
var serviceProvider = new ServiceProvider().AddMvc().BuildServiceProvider();
var modelMetadataProvider = serviceProvider.GetRequiredService<IModelMetadataProvider>();
```

This should work consistently across previous versions of MVC will giving you a type that's configured correctly for that version. Could you give that a try and see if it helps?

**Comment by tebeco** [comment]
good idea :D, so many possibility with that

**Comment by tebeco** [comment]
@pranavkm 

Almost fixed :
* the 3 test about the default `application/json` + `text/json` seems to also add `text/plain` <=== is there a behavior/breaking change in aspnetocre3 here ?

**Comment by pranavkm** [comment]
@tebeco I'll have to debug the tests to figure out what's going on. I don't believe we had any intentional changes here. 

I recall Swashbuckle uses the `BindingSource` to filter out `CancellationToken` types. Here's the relevant code: 

*  https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/a025be2cae11683ef473275041bd5090be6e3ce1/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs#L53-L70

* Previous test setup: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/d6a5c9adb086aa5033c9c1d0cd8e11f34b53c1e6/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/Fakes/FakeApiDescriptionGroupCollectionProvider.cs#L153

**Comment by tebeco** [comment]
> @tebeco I'll have to debug the tests to figure out what's going on. I don't believe we had any intentional changes here.

I pushed the code on the branch you have based the PR here if you'd like to take advantage of it
I attempted to make 2.x works too (so that i avoid the `#if NETCOREAPP3_0` but it have a side effect on swagger, so for now i won't focus on that

**Comment by tebeco** [comment]
Thx a lot for the help @pranavkm 

Not sure why / how the `CancellationToken/Source` went bad
Not really sure what happened during the PR in swashbuckle repo as I was looking for answers ^^.
Seems there was other PR and this one was closed

Thx A LOT for the time you took to help me understand a bit better some of the internals of Mvc / OpenApi

Sorry I kinda forget this PR here and then it came to a dead

**Pull request closed without merging**
